name: .NET Build and Run 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # allows manual trigger from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # use your desired Node version

      - name: Restore dependancies
        run: |
          cd dotnet-app
          dotnet restore

      - name: Build solution
        run: |
          cd dotnet-app
          dotnet build --no-restore

      - name: Run app
        run: dotnet run dotnet-app/dotnet-app.csproj