name: Listing the git projects

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}

      - name: Install dependancies
        run: |
          python -m install --upgrade pip
          pip install pytest
      
      - name: Run tests
        run: |
          cd src
          python -m pytest project_list.py