name: Python Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # allows manual trigger from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}

      - name: Install dependancies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Start application
        run: |
          cd python-app
          pip install -r requirements.txt
          python app.py
          sleep 5
          curl http://localhost:5000
